# Generated by Django 4.1 on 2023-07-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_template_reference_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(max_length=125),
        ),
    ]
